jobs:
  linux:
    needs: shared
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: 'echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV

        echo "$JAVA_HOME_11_X64/bin" >> $GITHUB_PATH

        sudo apt-get --quiet --yes install ninja-build libglu1-mesa-dev

        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave
        /usr/bin/g++ g++ /usr/bin/g++-9

        sudo update-alternatives --config gcc

        '
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      run: python3 script/build.py
    - continue-on-error: true
      run: python3 script/test.py
    - continue-on-error: true
      env:
        SPACE_TOKEN: ${{ secrets.SPACE_TOKEN }}
        USER_NAME: ${{ secrets.USER_NAME }}
      if: github.ref == 'refs/heads/master'
      run: python3 script/deploy_platform.py
    - continue-on-error: true
      if: github.ref != 'refs/heads/master'
      run: python3 script/deploy_platform.py --dry-run
    - continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: skija-linux-jar
        path: platform/target/*.jar
  macos:
    needs: shared
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: seanmiddleditch/gha-setup-ninja@master
    - continue-on-error: true
      run: 'echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV

        echo "$JAVA_HOME_11_X64/bin" >> $GITHUB_PATH

        '
    - continue-on-error: true
      run: python3 script/build.py --arch=${{ matrix.arch }}
    - continue-on-error: true
      if: ${{ matrix.arch == 'x64'}}
      name: Test
      run: python3 script/test.py
    - continue-on-error: true
      env:
        SPACE_TOKEN: ${{ secrets.SPACE_TOKEN }}
        USER_NAME: ${{ secrets.USER_NAME }}
      if: github.ref == 'refs/heads/master'
      run: python3 script/deploy_platform.py --arch=${{ matrix.arch }}
    - continue-on-error: true
      if: github.ref != 'refs/heads/master'
      run: python3 script/deploy_platform.py --arch=${{ matrix.arch }} --dry-run
    - continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: skija-macos-${{ matrix.arch }}-jar
        path: platform/target/*.jar
    strategy:
      matrix:
        arch:
        - x64
        - arm64
  shared:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      run: 'echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV

        echo "$JAVA_HOME_11_X64/bin" >> $GITHUB_PATH

        '
    - continue-on-error: true
      env:
        SPACE_TOKEN: ${{ secrets.SPACE_TOKEN }}
        USER_NAME: ${{ secrets.USER_NAME }}
      if: github.ref == 'refs/heads/master'
      run: python3 script/deploy_shared.py
    - continue-on-error: true
      if: github.ref != 'refs/heads/master'
      run: python3 script/deploy_shared.py --dry-run
    - continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: skija-shared-jar
        path: shared/target/*.jar
  windows:
    needs: shared
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: microsoft/setup-msbuild@v1
    - continue-on-error: true
      uses: ilammy/msvc-dev-cmd@v1
    - continue-on-error: true
      uses: seanmiddleditch/gha-setup-ninja@master
    - continue-on-error: true
      run: 'echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV

        echo "$JAVA_HOME_11_X64/bin" >> $GITHUB_PATH

        '
      shell: bash
    - continue-on-error: true
      run: python3 script/build.py
    - continue-on-error: true
      run: python3 script/test.py
      shell: bash
    - continue-on-error: true
      env:
        SPACE_TOKEN: ${{ secrets.SPACE_TOKEN }}
        USER_NAME: ${{ secrets.USER_NAME }}
      if: github.ref == 'refs/heads/master'
      run: python3 script/deploy_platform.py
    - continue-on-error: true
      if: github.ref != 'refs/heads/master'
      run: python3 script/deploy_platform.py --dry-run
    - continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: skija-windows-jar
        path: platform/target/*.jar
on:
  repository_dispatch:
    types: trigger-ga___build.yml
